#
# Examples for MSX 
#
# $Id: Makefile $
#

#include ../../libsrc/Make.config

CC = zcc

CFLAGS = +msx -vn -llib3d -lm -lndos -create-app -DAMALLOC -DMSX -O3 --opt-code-speed=all

EXECFILES = $(CFILES:.c=.cas)

all: beurette.rom

beurette.rom: src/beurette.o src/msx.o src/FixP.o
	$(CC) $(CFLAGS) -obeurette.rom src/beurette.c src/msx.c -lmsxbios -subtype=rom

clean:
	$(RM) *.obj *.sym *.map *.o* *.bin zcc_opt.def *.reloc *.cas *.COM *.img ex8 *.rom
