CC = zcc

CFLAGS = +gb -create-app -DGB -O0

all: demo.gb

demo.gb: src/demo.o src/gb.o
	$(CC) $(CFLAGS) -o demo.gb src/demo.o src/gb.o -lm -vn  -m -O3 --opt-code-speed=all -compiler=sdcc

clean:
	$(RM) *.obj *.sym *.map *.o* *.bin zcc_opt.def *.reloc *.cas *.COM *.img ex8 *.rom *.gb src/*.o