CC = zcc

CFLAGS = +msx  -compiler=sdcc -SO3 -vn -lndos -create-app -DMSX -O3 --opt-code-speed=all

all: demo.rom

demo.rom: src/demo.o src/msx.o
	$(CC) $(CFLAGS) -odemo.rom src/demo.c src/msx.c -lmsxbios -subtype=rom

clean:
	$(RM) *.obj *.sym *.map *.o* *.bin zcc_opt.def *.reloc *.cas *.COM *.img ex8 *.rom
