void cpct_drw_1_mode0();
void cpct_drw_2_mode0();
void cpct_drw_3_mode0();
void cpct_drw_4_mode0();
void cpct_drw_5_mode0();
void cpct_drw_6_mode0();
void cpct_drw_7_mode0();
void cpct_drw_8_mode0();
void cpct_drw_9_mode0();
void cpct_drw_10_mode0();
void cpct_drw_11_mode0();
void cpct_drw_12_mode0();
void cpct_drw_13_mode0();
void cpct_drw_14_mode0();
unsigned char cpct_drw_15_mode0();
unsigned char cpct_drw_16_mode0();
unsigned char cpct_drw_17_mode0();
unsigned char cpct_drw_18_mode0();
unsigned char cpct_drw_19_mode0();
unsigned char cpct_drw_20_mode0();
void cpct_drw_21_mode0();
void cpct_drw_22_mode0();

void cpct_drw_setLineColour_mode0(unsigned char);
void cpct_drw_plotClipped_mode0(signed int,signed int);
void cpct_drw_plotUnclipped_mode0(signed int,signed int);
void cpct_drw_line_mode0(signed int,signed int,signed int,signed int);
void cpct_drw_setClippingBox_mode0(signed int,signed int,signed int,signed int);

void cpct_drw_populateLineMasks_mode0();
void cpct_drw_restoreSysRegisters_mode0();
void cpct_drw_swapX_mode0();
void cpct_drw_swapY_mode0();

unsigned char cpct_drw_discardLine_mode0();
void cpct_drw_prepareLine_mode0();
unsigned char cpct_drw_singlePixel_mode0();
void cpct_drw_horizontalLine_mode0_asm();
unsigned char cpct_drw_horizontalLine_mode0();
void cpct_drw_verticalLine_mode0_asm();
unsigned char cpct_drw_verticalLine_mode0();
void cpct_drw_diagonalLineDown_mode0_asm();
unsigned char cpct_drw_diagonalLineDown_mode0();
void cpct_drw_diagonalLineUp_mode0_asm();
unsigned char cpct_drw_diagonalLineUp_mode0();
void cpct_drw_gentleLineDown_mode0();
void cpct_drw_steepLineDown_mode0();
void cpct_drw_gentleLineUp_mode0();
void cpct_drw_steepLineUp_mode0();
